### ISSUE TITLE
error: orphaned default and error: 'else' without 'if'

### ISSUE THREAD

**Issue by wltjr** [jflex-de/jflex#273]
Odd generated output with ```error: orphaned default``` and ```error: 'else' without 'if'```.

qdox 1.12.1 builds with 1.4.3, but not 1.6.1 bootstrapped
qdox 2 builds with 1.4.3 and 1.6.1 bootstrapped
jflex 1.6.1 builds with 1.6.1 bootstrapped but not 1.4.3

The errors are the same when jflex 1.6.1 bootstrapped fails on qdox 1.12.1, and when jflex 1.4.3 fails on jflex 1.6.1. That is odd and I cannot explain.

qdox 1.12.1 under 1.6.1 bootstrapped via binary fails
```
 * Compiling ...
src/java/JFlexLexer.java:1357: error: orphaned default
        default:
        ^
src/java/JFlexLexer.java:2051: error: 'else' without 'if'
          else {
          ^
2 errors
 * ERROR: dev-java/qdox-1.12.1-r10::os-xtoo failed (compile phase):
```

jflex 1.6.1  under 1.4.3 fails, under 1.6.1 bootstrapped via binary it builds fine
```
Writing code to "java/LexScan.java"
 * Compiling ...
src/main/java/LexScan.java:3697: error: orphaned default
          default:
          ^
src/main/java/LexScan.java:3626: error: 'else' without 'if'
      else {
      ^
2 errors
```

I have 1.4.3 built and running under Java 9. I do not believe the jdk version has anything to do with the generated output with errors. I think that has more to do with syntax or something.

**Comment by regisd** [comment]
@wltjr William, this is a severe bug in the code generation.

I'm afraid I'm lost in the repro steps, though. Can you clarify one example breakage:

- what `.jflex` definition
- and what released version

Thanks a star!

**Comment by wltjr** [comment]
The first one was [qdox 1.12.1](https://github.com/codehaus/qdox/tree/qdox-1.12.1/src/grammar) and jflex 1.6.1.
```
jflex --skel skeleton.inner lexer.flex
```

Then for jflex itself using jflex 1.4.3 to process [jflex 1.6.1](https://github.com/jflex-de/jflex/tree/master/jflex/src/main/jflex) files.
```
jflex --skel skeleton.nested LexScan.flex
```

**Comment by lsf37** [comment]
Can you clarify from which jflex release each of the skeleton files are? They sometimes change over releases (this might actually be the cause of the problem, although I'd expect an error message by jflex, so there'd be something to fix in any case).

**Comment by wltjr** [comment]
Sorry I meant to provide a link to a tagged version above, [these from jflex 1.6.1](https://github.com/jflex-de/jflex/tree/v1.6.1/jflex/src/main/jflex), jflex 1.4.3 cannot process them. That maybe expected since its an older version of jflex processing files for a newer version of jflex. But the error is the same as I get with qdox using jflex 1.6.1. Not sure the error is specific to either 1.4.3 or 1.6.1, seems either version can have the same issue.

**Comment by lsf37** [comment]
cool, thanks, will try to reproduce (might take a bit, though, because work is taking over again)

**Comment by wltjr** [comment]
No worries, I have worked around it for the most part. An odd issue, surely not a priority. Just something I thought you all may want to be aware of in case others run into the same or similar. I doubt it is very common and may have existed for some time.

**Comment by regisd** [comment]
For qdox 1.12.1
============

Both errors come from `skeleton.inner`, as demonstrated by:

```
git clone git clone https://github.com/codehaus/qdox.git --branch qdox-1.12.1
cd qdox
```

Then apply [skeleton.patch.txt](https://github.com/jflex-de/jflex/files/2388164/skeleton.patch.txt)

```
diff --git a/src/grammar/skeleton.inner b/src/grammar/skeleton.inner
index 42cc796e..87a5a451 100644
--- a/src/grammar/skeleton.inner
+++ b/src/grammar/skeleton.inner
@@ -408,12 +408,12 @@
 --- char count update
 
 --- actions
-        default: 
+        default: // SKELETON.INNER
           if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
             zzAtEOF = true;
 --- eofvalue
           } 
-          else {
+          else { // SKELETON.INNER
 --- no match
           }
       }
```

```sh
java -jar /usr/local/google/home/regisd/.m2/repository/de/jflex/jflex/1.6.1/jflex-1.6.1.jar --skel src/grammar/skeleton.inner src/grammar/lexer.flex
javac src/grammar/JFlexLexer.java
```
which produces 
```
javac src/grammar/JFlexLexer.java 
src/grammar/JFlexLexer.java:1338: error: orphaned default
        default: // SKELETON.INNER
        ^
src/grammar/JFlexLexer.java:2032: error: 'else' without 'if'
          else { // SKELETON.INNER
          ^
2 errors
```

For JFlex
========

```sh
git clone https://github.com/jflex-de/jflex.git
cd jflex
./mvnw dependency:get de.jflex:jflex:1.4.3:jar
git co v1.6.1 
java -jar ~/.m2/repository/de/jflex/jflex/1.4.3/jflex-1.4.3.jar --skel ./jflex/src/main/jflex/skeleton.nested ./jflex/src/main/jflex/LexScan.flex 
```

And I obtain:
```
Reading skeleton file "./jflex/src/main/jflex/skeleton.nested".
Reading "./jflex/src/main/jflex/LexScan.flex"

Error in file "./jflex/src/main/jflex/LexScan.flex" (line 43): 
Unkown %-option
%inputstreamctor false
^
1 error, 0 warnings.
``

And that's expected because v1.4.3 didn't support option `%inputstreamctor` (see https://github.com/jflex-de/jflex/releases/tag/release_1_5_0)

**Comment by regisd** [comment]
Just to make it clear. You cannot use the skeleton of 1.6.1 with the 1.4.3 generator. You can however do:
```sh
git co v1.6.1
java -jar ~/.m2/repository/de/jflex/jflex/1.4.3/jflex-1.4.3.jar ./jflex/src/main/jflex/LexScan.flex 
```

**Comment by wltjr** [comment]
@regisd that should be fixed for 1.6.1 You should be able to use a previous version to build a newer version as part of bootstrap. I can build 1.4.3 from source, without need of JFlex. I should be able to use 1.4.3 to build 1.6.1. That is how I build other things like antlr and stringtemplate for example. Otherwise how does one build 1.6.1, without needing a binary of 1.6.1 already?

Thus far I have [avoided 1.6.1](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java/jflex) and just stuck with 1.4.3. Not sure I have a need to package newer, though the [package is ready](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/jflex/jflex-9999.ebuild#L53) for 1.6.1 not just 1.4.3.

**Comment by regisd** [comment]
1.4.3 was shipping the generated sources (made with 1.4.2 https://github.com/jflex-de/jflex/blob/release_1_4_3/jflex/src/JFlex/LexScan.java) 

If you want the same thing, for 1.6.1, just fetch https://github.com/jflex-de/jflex/tree/sources-v1.6.1 (see #271)

If you want to generated sources of 1.6.1 with 1.4.3, just run 
```
java -jar jflex-1.4.3.jar ./jflex/src/main/jflex/LexScan.flex 
```

You cannot mix the skeleton of 1.6.1 with the emitter of 1.4.3. That's like trying to compile gcc 8.2 with the header files of gcc 7.3

**Comment by wltjr** [comment]
Ah ok that makes sense. I did not know I needed to use different skeleton files.

**Comment by wltjr** [comment]
Thanks for that information! I never did read the documentation. I just saw the skeleton option for the cli and noticed skeleton files. It was my mistake to use the skeleton with the cli rather than just using them for inclusion in the jar for internal usage.
